// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAv2wl77Qvh2KJ71t5mlIW8-iw0lM9Kh5M',
    appId: '1:775127270256:web:0943e29e2757badca445b5',
    messagingSenderId: '775127270256',
    projectId: 'cmsc-23-project-group-04',
    authDomain: 'cmsc-23-project-group-04.firebaseapp.com',
    storageBucket: 'cmsc-23-project-group-04.appspot.com',
    measurementId: 'G-BZWRSYXH4Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCq3rKC3QHkmUKbGMME2ke07s7gEaDaX9Y',
    appId: '1:775127270256:android:e39e97af9e9c5f79a445b5',
    messagingSenderId: '775127270256',
    projectId: 'cmsc-23-project-group-04',
    storageBucket: 'cmsc-23-project-group-04.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD81Achxp_Fq3YkE6yjmLc45hDoRnglLhc',
    appId: '1:775127270256:ios:69f4a59d16d8d9d1a445b5',
    messagingSenderId: '775127270256',
    projectId: 'cmsc-23-project-group-04',
    storageBucket: 'cmsc-23-project-group-04.appspot.com',
    iosBundleId: 'com.example.cmsc23Proj',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD81Achxp_Fq3YkE6yjmLc45hDoRnglLhc',
    appId: '1:775127270256:ios:69f4a59d16d8d9d1a445b5',
    messagingSenderId: '775127270256',
    projectId: 'cmsc-23-project-group-04',
    storageBucket: 'cmsc-23-project-group-04.appspot.com',
    iosBundleId: 'com.example.cmsc23Proj',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAv2wl77Qvh2KJ71t5mlIW8-iw0lM9Kh5M',
    appId: '1:775127270256:web:0059c71f89c3e9d5a445b5',
    messagingSenderId: '775127270256',
    projectId: 'cmsc-23-project-group-04',
    authDomain: 'cmsc-23-project-group-04.firebaseapp.com',
    storageBucket: 'cmsc-23-project-group-04.appspot.com',
    measurementId: 'G-QC6DEJ5CQT',
  );
}
